# Site settings
title: Mingrui Cao's Page
name: Mingrui Cao # your name
email: leo201313@foxmail.com # your email address
description: >
    A page for Mingrui Cao to record his experience. # this means to ignore newlines until "baseurl:"
baseurl: "/leo201313.github.io" # the subpath of your site, e.g. /blog
url: "https://leo201313.github.io" # the base hostname & protocol for your site
twitter_username: MingruiCao # your Twitter username
github_username: leo201313 # your Github username
disqus_username: # your disqus username

google-analytics: UA-190924560-1 # add it if you have one

skillstree: true # turn on or off the skills tree in about page

# Build settings
permalink: none
markdown: kramdown
